[package]
name = "nespera"
version = "0.1.0"
authors = ["Caio Souza <caiophilipevs@gmail.com>"]
edition = '2018'

[dependencies]
pretty-hex = "0.1.0"
log = "0.4.0"
env_logger = "0.6.0"
image = "*"
chrono = "0.4"
