// Address mode for operations
pub mod mode {
    pub enum Nop { Implied, Immediate, ZeroPage, ZeroPageX, Absolute, AbsoluteX }

    pub enum Lda { Immediate, ZeroPage, ZeroPageX, Absolute, AbsoluteX, AbsoluteY, IndirectX, IndirectY }

    pub enum Ldx { Immediate, ZeroPage, ZeroPageY, Absolute, AbsoluteY }

    pub enum Ldy { Immediate, ZeroPage, ZeroPageX, Absolute, AbsoluteX }
}

// Operations to execute
pub enum Opcode {
    None,
    Nop(mode::Nop),
    Stp,
    Lda(mode::Lda),
    Ldx(mode::Ldx),
    Ldy(mode::Ldy),
}

pub const OPCODES: [Opcode; 256] = [
    /*00*/ Opcode::None,
    /*01*/ Opcode::None,
    /*02*/ Opcode::Stp,
    /*03*/ Opcode::None,
    /*04*/ Opcode::Nop(mode::Nop::ZeroPage),
    /*05*/ Opcode::None,
    /*06*/ Opcode::None,
    /*07*/ Opcode::None,
    /*08*/ Opcode::None,
    /*09*/ Opcode::None,
    /*0A*/ Opcode::Nop(mode::Nop::Implied),
    /*0B*/ Opcode::None,
    /*0C*/ Opcode::Nop(mode::Nop::Absolute),
    /*0D*/ Opcode::None,
    /*0E*/ Opcode::None,
    /*0F*/ Opcode::None,
    /**/
    /*10*/ Opcode::None,
    /*11*/ Opcode::None,
    /*12*/ Opcode::Stp,
    /*13*/ Opcode::None,
    /*14*/ Opcode::Nop(mode::Nop::ZeroPageX),
    /*15*/ Opcode::None,
    /*16*/ Opcode::None,
    /*17*/ Opcode::None,
    /*18*/ Opcode::None,
    /*19*/ Opcode::None,
    /*1A*/ Opcode::Nop(mode::Nop::Implied),
    /*1B*/ Opcode::None,
    /*1C*/ Opcode::Nop(mode::Nop::AbsoluteX),
    /*1D*/ Opcode::None,
    /*1E*/ Opcode::None,
    /*1F*/ Opcode::None,
    /**/
    /*20*/ Opcode::None,
    /*21*/ Opcode::None,
    /*22*/ Opcode::Stp,
    /*23*/ Opcode::None,
    /*24*/ Opcode::None,
    /*25*/ Opcode::None,
    /*26*/ Opcode::None,
    /*27*/ Opcode::None,
    /*28*/ Opcode::None,
    /*29*/ Opcode::None,
    /*2A*/ Opcode::None,
    /*2B*/ Opcode::None,
    /*2C*/ Opcode::None,
    /*2D*/ Opcode::None,
    /*2E*/ Opcode::None,
    /*2F*/ Opcode::None,
    /**/
    /*30*/ Opcode::None,
    /*31*/ Opcode::None,
    /*32*/ Opcode::Stp,
    /*33*/ Opcode::None,
    /*34*/ Opcode::Nop(mode::Nop::ZeroPageX),
    /*35*/ Opcode::None,
    /*36*/ Opcode::None,
    /*37*/ Opcode::None,
    /*38*/ Opcode::None,
    /*39*/ Opcode::None,
    /*3A*/ Opcode::Nop(mode::Nop::Implied),
    /*3B*/ Opcode::None,
    /*3C*/ Opcode::Nop(mode::Nop::AbsoluteX),
    /*3D*/ Opcode::None,
    /*3E*/ Opcode::None,
    /*3F*/ Opcode::None,
    /**/
    /*40*/ Opcode::None,
    /*41*/ Opcode::None,
    /*42*/ Opcode::Stp,
    /*43*/ Opcode::None,
    /*44*/ Opcode::Nop(mode::Nop::ZeroPage),
    /*45*/ Opcode::None,
    /*46*/ Opcode::None,
    /*47*/ Opcode::None,
    /*48*/ Opcode::None,
    /*49*/ Opcode::None,
    /*4A*/ Opcode::None,
    /*4B*/ Opcode::None,
    /*4C*/ Opcode::None,
    /*4D*/ Opcode::None,
    /*4E*/ Opcode::None,
    /*4F*/ Opcode::None,
    /**/
    /*50*/ Opcode::None,
    /*51*/ Opcode::None,
    /*52*/ Opcode::Stp,
    /*53*/ Opcode::None,
    /*54*/ Opcode::Nop(mode::Nop::ZeroPageX),
    /*55*/ Opcode::None,
    /*56*/ Opcode::None,
    /*57*/ Opcode::None,
    /*58*/ Opcode::None,
    /*59*/ Opcode::None,
    /*5A*/ Opcode::Nop(mode::Nop::Implied),
    /*5B*/ Opcode::None,
    /*5C*/ Opcode::Nop(mode::Nop::AbsoluteX),
    /*5D*/ Opcode::None,
    /*5E*/ Opcode::None,
    /*5F*/ Opcode::None,
    /**/
    /*60*/ Opcode::None,
    /*61*/ Opcode::None,
    /*62*/ Opcode::Stp,
    /*63*/ Opcode::None,
    /*64*/ Opcode::Nop(mode::Nop::ZeroPage),
    /*65*/ Opcode::None,
    /*66*/ Opcode::None,
    /*67*/ Opcode::None,
    /*68*/ Opcode::None,
    /*69*/ Opcode::None,
    /*6A*/ Opcode::None,
    /*6B*/ Opcode::None,
    /*6C*/ Opcode::None,
    /*6D*/ Opcode::None,
    /*6E*/ Opcode::None,
    /*6F*/ Opcode::None,
    /**/
    /*70*/ Opcode::None,
    /*71*/ Opcode::None,
    /*72*/ Opcode::Stp,
    /*73*/ Opcode::None,
    /*74*/ Opcode::Nop(mode::Nop::ZeroPageX),
    /*75*/ Opcode::None,
    /*76*/ Opcode::None,
    /*77*/ Opcode::None,
    /*78*/ Opcode::None,
    /*79*/ Opcode::None,
    /*7A*/ Opcode::Nop(mode::Nop::Implied),
    /*7B*/ Opcode::None,
    /*7C*/ Opcode::Nop(mode::Nop::AbsoluteX),
    /*7D*/ Opcode::None,
    /*7E*/ Opcode::None,
    /*7F*/ Opcode::None,
    /**/
    /*80*/ Opcode::Nop(mode::Nop::Immediate),
    /*81*/ Opcode::None,
    /*82*/ Opcode::Nop(mode::Nop::Immediate),
    /*83*/ Opcode::None,
    /*84*/ Opcode::None,
    /*85*/ Opcode::None,
    /*86*/ Opcode::None,
    /*87*/ Opcode::None,
    /*88*/ Opcode::None,
    /*89*/ Opcode::Nop(mode::Nop::Immediate),
    /*8A*/ Opcode::None,
    /*8B*/ Opcode::None,
    /*8C*/ Opcode::None,
    /*8D*/ Opcode::None,
    /*8E*/ Opcode::None,
    /*8F*/ Opcode::None,
    /**/
    /*90*/ Opcode::None,
    /*91*/ Opcode::None,
    /*92*/ Opcode::Stp,
    /*93*/ Opcode::None,
    /*94*/ Opcode::None,
    /*95*/ Opcode::None,
    /*96*/ Opcode::None,
    /*97*/ Opcode::None,
    /*98*/ Opcode::None,
    /*99*/ Opcode::None,
    /*9A*/ Opcode::None,
    /*9B*/ Opcode::None,
    /*9C*/ Opcode::None,
    /*9D*/ Opcode::None,
    /*9E*/ Opcode::None,
    /*9F*/ Opcode::None,
    /**/
    /*A0*/ Opcode::Ldy(mode::Ldy::Immediate),
    /*A1*/ Opcode::Lda(mode::Lda::IndirectX),
    /*A2*/ Opcode::Ldx(mode::Ldx::Immediate),
    /*A3*/ Opcode::None,
    /*A4*/ Opcode::Ldy(mode::Ldy::ZeroPage),
    /*A5*/ Opcode::Lda(mode::Lda::ZeroPage),
    /*A6*/ Opcode::Ldx(mode::Ldx::ZeroPage),
    /*A7*/ Opcode::None,
    /*A8*/ Opcode::None,
    /*A9*/ Opcode::Lda(mode::Lda::Immediate),
    /*AA*/ Opcode::None,
    /*AB*/ Opcode::None,
    /*AC*/ Opcode::Ldy(mode::Ldy::Absolute),
    /*AD*/ Opcode::Lda(mode::Lda::Absolute),
    /*AE*/ Opcode::Ldx(mode::Ldx::Absolute),
    /*AF*/ Opcode::None,
    /**/
    /*B0*/ Opcode::None,
    /*B1*/ Opcode::Lda(mode::Lda::IndirectY),
    /*B2*/ Opcode::Stp,
    /*B3*/ Opcode::None,
    /*B4*/ Opcode::Ldy(mode::Ldy::ZeroPageX),
    /*B5*/ Opcode::Lda(mode::Lda::ZeroPageX),
    /*B6*/ Opcode::Ldx(mode::Ldx::ZeroPageY),
    /*B7*/ Opcode::None,
    /*B8*/ Opcode::None,
    /*B9*/ Opcode::Lda(mode::Lda::AbsoluteY),
    /*BA*/ Opcode::None,
    /*BB*/ Opcode::None,
    /*BC*/ Opcode::Ldy(mode::Ldy::AbsoluteX),
    /*BD*/ Opcode::Lda(mode::Lda::AbsoluteX),
    /*BE*/ Opcode::Ldx(mode::Ldx::AbsoluteY),
    /*BF*/ Opcode::None,
    /**/
    /*C0*/ Opcode::None,
    /*C1*/ Opcode::None,
    /*C2*/ Opcode::Nop(mode::Nop::Immediate),
    /*C3*/ Opcode::None,
    /*C4*/ Opcode::None,
    /*C5*/ Opcode::None,
    /*C6*/ Opcode::None,
    /*C7*/ Opcode::None,
    /*C8*/ Opcode::None,
    /*C9*/ Opcode::None,
    /*CA*/ Opcode::None,
    /*CB*/ Opcode::None,
    /*CC*/ Opcode::None,
    /*CD*/ Opcode::None,
    /*CE*/ Opcode::None,
    /*CF*/ Opcode::None,
    /**/
    /*D0*/ Opcode::None,
    /*D1*/ Opcode::None,
    /*D2*/ Opcode::Stp,
    /*D3*/ Opcode::None,
    /*D4*/ Opcode::Nop(mode::Nop::ZeroPageX),
    /*D5*/ Opcode::None,
    /*D6*/ Opcode::None,
    /*D7*/ Opcode::None,
    /*D8*/ Opcode::None,
    /*D9*/ Opcode::None,
    /*DA*/ Opcode::Nop(mode::Nop::Implied),
    /*DB*/ Opcode::None,
    /*DC*/ Opcode::Nop(mode::Nop::AbsoluteX),
    /*DD*/ Opcode::None,
    /*DE*/ Opcode::None,
    /*DF*/ Opcode::None,
    /**/
    /*E0*/ Opcode::None,
    /*E1*/ Opcode::None,
    /*E2*/ Opcode::Nop(mode::Nop::Immediate),
    /*E3*/ Opcode::None,
    /*E4*/ Opcode::None,
    /*E5*/ Opcode::None,
    /*E6*/ Opcode::None,
    /*E7*/ Opcode::None,
    /*E8*/ Opcode::None,
    /*E9*/ Opcode::None,
    /*EA*/ Opcode::Nop(mode::Nop::Implied),
    /*EB*/ Opcode::None,
    /*EC*/ Opcode::None,
    /*ED*/ Opcode::None,
    /*EE*/ Opcode::None,
    /*EF*/ Opcode::None,
    /**/
    /*F0*/ Opcode::None,
    /*F1*/ Opcode::None,
    /*F2*/ Opcode::Stp,
    /*F3*/ Opcode::None,
    /*F4*/ Opcode::Nop(mode::Nop::ZeroPageX),
    /*F5*/ Opcode::None,
    /*F6*/ Opcode::None,
    /*F7*/ Opcode::None,
    /*F8*/ Opcode::None,
    /*F9*/ Opcode::None,
    /*FA*/ Opcode::Nop(mode::Nop::Implied),
    /*FB*/ Opcode::None,
    /*FC*/ Opcode::Nop(mode::Nop::AbsoluteX),
    /*FD*/ Opcode::None,
    /*FE*/ Opcode::None,
    /*FF*/ Opcode::None,
];
