// Address mode for operations
pub mod mode {
    pub enum Nop { Implicit, Accumulator, Immediate, ZeroPage }

    //pub enum Lda { Immediate, ZeroPage, ZeroPageX, Absolute, AbsoluteX, AbsoluteY, IndirectX, IndirectY }
}

// Operations to execute
pub enum Opcode {
    // Not implemented.
    None,

    // No operation
    Nop(mode::Nop),

    // Kill the processor
    Stp,
}

pub const OPCODES: [Opcode; 256] = [
    /*00*/ Opcode::None,
    /*01*/ Opcode::None,
    /*02*/ Opcode::Stp,
    /*03*/ Opcode::None,
    /*04*/ Opcode::Nop(mode::Nop::ZeroPage),
    /*05*/ Opcode::None,
    /*06*/ Opcode::None,
    /*07*/ Opcode::None,
    /*08*/ Opcode::None,
    /*09*/ Opcode::None,
    /*0a*/ Opcode::Nop(mode::Nop::Implicit),
    /*0b*/ Opcode::None,
    /*0c*/ Opcode::Nop(mode::Nop::Accumulator),
    /*0d*/ Opcode::None,
    /*0e*/ Opcode::None,
    /*0f*/ Opcode::None,
    /**/
    /*10*/ Opcode::None,
    /*11*/ Opcode::None,
    /*12*/ Opcode::Stp,
    /*13*/ Opcode::None,
    /*14*/ Opcode::None,
    /*15*/ Opcode::None,
    /*16*/ Opcode::None,
    /*17*/ Opcode::None,
    /*18*/ Opcode::None,
    /*19*/ Opcode::None,
    /*1a*/ Opcode::Nop(mode::Nop::Implicit),
    /*1b*/ Opcode::None,
    /*1c*/ Opcode::None,
    /*1d*/ Opcode::None,
    /*1e*/ Opcode::None,
    /*1f*/ Opcode::None,
    /**/
    /*20*/ Opcode::None,
    /*21*/ Opcode::None,
    /*22*/ Opcode::Stp,
    /*23*/ Opcode::None,
    /*24*/ Opcode::None,
    /*25*/ Opcode::None,
    /*26*/ Opcode::None,
    /*27*/ Opcode::None,
    /*28*/ Opcode::None,
    /*29*/ Opcode::None,
    /*2a*/ Opcode::None,
    /*2b*/ Opcode::None,
    /*2c*/ Opcode::None,
    /*2d*/ Opcode::None,
    /*2e*/ Opcode::None,
    /*2f*/ Opcode::None,
    /**/
    /*30*/ Opcode::None,
    /*31*/ Opcode::None,
    /*32*/ Opcode::Stp,
    /*33*/ Opcode::None,
    /*34*/ Opcode::None,
    /*35*/ Opcode::None,
    /*36*/ Opcode::None,
    /*37*/ Opcode::None,
    /*38*/ Opcode::None,
    /*39*/ Opcode::None,
    /*3a*/ Opcode::Nop(mode::Nop::Implicit),
    /*3b*/ Opcode::None,
    /*3c*/ Opcode::None,
    /*3d*/ Opcode::None,
    /*3e*/ Opcode::None,
    /*3f*/ Opcode::None,
    /**/
    /*40*/ Opcode::None,
    /*41*/ Opcode::None,
    /*42*/ Opcode::Stp,
    /*43*/ Opcode::None,
    /*44*/ Opcode::Nop(mode::Nop::ZeroPage),
    /*45*/ Opcode::None,
    /*46*/ Opcode::None,
    /*47*/ Opcode::None,
    /*48*/ Opcode::None,
    /*49*/ Opcode::None,
    /*4a*/ Opcode::None,
    /*4b*/ Opcode::None,
    /*4c*/ Opcode::None,
    /*4d*/ Opcode::None,
    /*4e*/ Opcode::None,
    /*4f*/ Opcode::None,
    /**/
    /*50*/ Opcode::None,
    /*51*/ Opcode::None,
    /*52*/ Opcode::Stp,
    /*53*/ Opcode::None,
    /*54*/ Opcode::None,
    /*55*/ Opcode::None,
    /*56*/ Opcode::None,
    /*57*/ Opcode::None,
    /*58*/ Opcode::None,
    /*59*/ Opcode::None,
    /*5a*/ Opcode::Nop(mode::Nop::Implicit),
    /*5b*/ Opcode::None,
    /*5c*/ Opcode::None,
    /*5d*/ Opcode::None,
    /*5e*/ Opcode::None,
    /*5f*/ Opcode::None,
    /**/
    /*60*/ Opcode::None,
    /*61*/ Opcode::None,
    /*62*/ Opcode::Stp,
    /*63*/ Opcode::None,
    /*64*/ Opcode::Nop(mode::Nop::ZeroPage),
    /*65*/ Opcode::None,
    /*66*/ Opcode::None,
    /*67*/ Opcode::None,
    /*68*/ Opcode::None,
    /*69*/ Opcode::None,
    /*6a*/ Opcode::None,
    /*6b*/ Opcode::None,
    /*6c*/ Opcode::None,
    /*6d*/ Opcode::None,
    /*6e*/ Opcode::None,
    /*6f*/ Opcode::None,
    /**/
    /*70*/ Opcode::None,
    /*71*/ Opcode::None,
    /*72*/ Opcode::Stp,
    /*73*/ Opcode::None,
    /*74*/ Opcode::None,
    /*75*/ Opcode::None,
    /*76*/ Opcode::None,
    /*77*/ Opcode::None,
    /*78*/ Opcode::None,
    /*79*/ Opcode::None,
    /*7a*/ Opcode::Nop(mode::Nop::Implicit),
    /*7b*/ Opcode::None,
    /*7c*/ Opcode::None,
    /*7d*/ Opcode::None,
    /*7e*/ Opcode::None,
    /*7f*/ Opcode::None,
    /**/
    /*80*/ Opcode::Nop(mode::Nop::Immediate),
    /*81*/ Opcode::None,
    /*82*/ Opcode::Nop(mode::Nop::Immediate),
    /*83*/ Opcode::None,
    /*84*/ Opcode::None,
    /*85*/ Opcode::None,
    /*86*/ Opcode::None,
    /*87*/ Opcode::None,
    /*88*/ Opcode::None,
    /*89*/ Opcode::Nop(mode::Nop::Immediate),
    /*8a*/ Opcode::None,
    /*8b*/ Opcode::None,
    /*8c*/ Opcode::None,
    /*8d*/ Opcode::None,
    /*8e*/ Opcode::None,
    /*8f*/ Opcode::None,
    /**/
    /*90*/ Opcode::None,
    /*91*/ Opcode::None,
    /*92*/ Opcode::Stp,
    /*93*/ Opcode::None,
    /*94*/ Opcode::None,
    /*95*/ Opcode::None,
    /*96*/ Opcode::None,
    /*97*/ Opcode::None,
    /*98*/ Opcode::None,
    /*99*/ Opcode::None,
    /*9a*/ Opcode::None,
    /*9b*/ Opcode::None,
    /*9c*/ Opcode::None,
    /*9d*/ Opcode::None,
    /*9e*/ Opcode::None,
    /*9f*/ Opcode::None,
    /**/
    /*a0*/ Opcode::None,
    /*a1*/ Opcode::None,
    /*a2*/ Opcode::None,
    /*a3*/ Opcode::None,
    /*a4*/ Opcode::None,
    /*a5*/ Opcode::None,
    /*a6*/ Opcode::None,
    /*a7*/ Opcode::None,
    /*a8*/ Opcode::None,
    /*a9*/ Opcode::None,
    /*aa*/ Opcode::None,
    /*ab*/ Opcode::None,
    /*ac*/ Opcode::None,
    /*ad*/ Opcode::None,
    /*ae*/ Opcode::None,
    /*af*/ Opcode::None,
    /**/
    /*b0*/ Opcode::None,
    /*b1*/ Opcode::None,
    /*b2*/ Opcode::Stp,
    /*b3*/ Opcode::None,
    /*b4*/ Opcode::None,
    /*b5*/ Opcode::None,
    /*b6*/ Opcode::None,
    /*b7*/ Opcode::None,
    /*b8*/ Opcode::None,
    /*b9*/ Opcode::None,
    /*ba*/ Opcode::None,
    /*bb*/ Opcode::None,
    /*bc*/ Opcode::None,
    /*bd*/ Opcode::None,
    /*be*/ Opcode::None,
    /*bf*/ Opcode::None,
    /**/
    /*c0*/ Opcode::None,
    /*c1*/ Opcode::None,
    /*c2*/ Opcode::Nop(mode::Nop::Immediate),
    /*c3*/ Opcode::None,
    /*c4*/ Opcode::None,
    /*c5*/ Opcode::None,
    /*c6*/ Opcode::None,
    /*c7*/ Opcode::None,
    /*c8*/ Opcode::None,
    /*c9*/ Opcode::None,
    /*ca*/ Opcode::None,
    /*cb*/ Opcode::None,
    /*cc*/ Opcode::None,
    /*cd*/ Opcode::None,
    /*ce*/ Opcode::None,
    /*cf*/ Opcode::None,
    /**/
    /*d0*/ Opcode::None,
    /*d1*/ Opcode::None,
    /*d2*/ Opcode::Stp,
    /*d3*/ Opcode::None,
    /*d4*/ Opcode::None,
    /*d5*/ Opcode::None,
    /*d6*/ Opcode::None,
    /*d7*/ Opcode::None,
    /*d8*/ Opcode::None,
    /*d9*/ Opcode::None,
    /*da*/ Opcode::Nop(mode::Nop::Implicit),
    /*db*/ Opcode::None,
    /*dc*/ Opcode::None,
    /*dd*/ Opcode::None,
    /*de*/ Opcode::None,
    /*df*/ Opcode::None,
    /**/
    /*e0*/ Opcode::None,
    /*e1*/ Opcode::None,
    /*e2*/ Opcode::Nop(mode::Nop::Immediate),
    /*e3*/ Opcode::None,
    /*e4*/ Opcode::None,
    /*e5*/ Opcode::None,
    /*e6*/ Opcode::None,
    /*e7*/ Opcode::None,
    /*e8*/ Opcode::None,
    /*e9*/ Opcode::None,
    /*ea*/ Opcode::Nop(mode::Nop::Implicit),
    /*eb*/ Opcode::None,
    /*ec*/ Opcode::None,
    /*ed*/ Opcode::None,
    /*ee*/ Opcode::None,
    /*ef*/ Opcode::None,
    /**/
    /*f0*/ Opcode::None,
    /*f1*/ Opcode::None,
    /*f2*/ Opcode::Stp,
    /*f3*/ Opcode::None,
    /*f4*/ Opcode::None,
    /*f5*/ Opcode::None,
    /*f6*/ Opcode::None,
    /*f7*/ Opcode::None,
    /*f8*/ Opcode::None,
    /*f9*/ Opcode::None,
    /*fa*/ Opcode::Nop(mode::Nop::Implicit),
    /*fb*/ Opcode::None,
    /*fc*/ Opcode::None,
    /*fd*/ Opcode::None,
    /*fe*/ Opcode::None,
    /*ff*/ Opcode::None,
];
